version: '3.8'

services:

  db:
    image: mysql:8.0
    # command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db-data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: password
      # MYSQL_DATABASE: mydatabase
      TZ: 'Asia/Tokyo'
    
  adminer:
    image: adminer:latest
    depends_on:
      - db
    ports:
      - 8080:8080

  app:
    build: .
    tty: true
    volumes:
      - ./app:/go/src/app

volumes:
  db-data:
    driver: local
