version: '3.8'

services:

  db:
    image: mysql:8.0
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_DATABASE: devdb
      MYSQL_ROOT_PASSWORD: password
      TZ: 'Asia/Tokyo'
    
  adminer:
    image: adminer:latest
    depends_on:
      - db
    ports:
      - 8080:8080

  app:
    build: .
    tty: true
    volumes:
      - ./app:/go/src/app

volumes:
  mysql-data:
    driver: local
